### ISSUE TITLE
installation bugs

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/GeoMop#268]
**installation from DEB**:
- during installation:
   ```
    ln: failed to create symbolic link '/usr/share/geomop/env/geomop/lib/python3.4/PyQt5': No such file or directory
    ln: failed to create symbolic link '/usr/share/geomop/env/geomop/lib/python3.4/sip.so': No such file or directory
   ```
   ... potential problem.
- execution of `geomop-me`:
 ~/local$ geomop-me
	Traceback (most recent call last):
	  File "/usr/share/geomop/src/ModelEditor/model_editor.py", line 19, in <module>
	    from ModelEditor.meconfig import MEConfig as cfg
	  File "/usr/share/geomop/src/ModelEditor/meconfig.py", line 28, in <module>
	    from change_rules import make_changes
	ModuleNotFoundError: No module named 'change_rules'

- execution of 'geomop-le':
Traceback (most recent call last):
  File "/usr/share/geomop/src/ModelEditor/model_editor.py", line 19, in <module>
    from ModelEditor.meconfig import MEConfig as cfg
  File "/usr/share/geomop/src/ModelEditor/meconfig.py", line 28, in <module>
    from change_rules import make_changes
ModuleNotFoundError: No module named 'change_rules'
 ~/local$ geomop-
geomop-le  geomop-me  
 ~/local$ geomop-le
	PPATH:  ['/usr/share/geomop/src/LayerEditor', '/usr/share/geomop/env/geomop/lib/python36.zip', '/usr/share/geomop/env/geomop/lib/python3.6', '/usr/share/geomop/env/geomop/lib/python3.6/lib-dynload', '/usr/lib/python3.6', '/usr/share/geomop/env/geomop/lib/python3.6/site-packages', '/home/jb/.local/lib/python3.6/site-packages', '/usr/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/share/geomop/src', '/usr/share/geomop/submodules/intersections/src', '/usr/share/geomop/src/gm_base/b_spline/../../intersections/src']
	Traceback (most recent call last):
	  File "/usr/share/geomop/src/LayerEditor/layer_editor.py", line 12, in <module>
	    from LayerEditor.ui import MainWindow
	  File "/usr/share/geomop/src/LayerEditor/ui/__init__.py", line 6, in <module>
	    from .mainwindow import MainWindow
	  File "/usr/share/geomop/src/LayerEditor/ui/mainwindow.py", line 8, in <module>
	    from . import panels
	  File "/usr/share/geomop/src/LayerEditor/ui/panels/__init__.py", line 1, in <module>
	    from .diagram import Diagram
	  File "/usr/share/geomop/src/LayerEditor/ui/panels/diagram.py", line 6, in <module>
	    from ..data import diagram_structures as struc
	  File "/usr/share/geomop/src/LayerEditor/ui/data/__init__.py", line 3, in <module>
	    from .le_serializer import LESerializer
	  File "/usr/share/geomop/src/LayerEditor/ui/data/le_serializer.py", line 5, in <module>
	    from gm_base.geometry_files.geometry_factory import GeometryFactory
	  File "/usr/share/geomop/src/gm_base/geometry_files/geometry_factory.py", line 7, in <module>
	    from .bspline_io import bs_zsurface_read, bs_zsurface_write
	  File "/usr/share/geomop/src/gm_base/geometry_files/bspline_io.py", line 4, in <module>
	    import bspline as bs
	ModuleNotFoundError: No module named 'bspline'

- missing `/usr/bin/geomop-jp`

**Comment by radeksrb** [comment]
Fixed.
