### ISSUE TITLE
JobsScheduler - Testování

### ISSUE THREAD

**Issue by johnymachine** [GeoMop/GeoMop#76]
Testování jednotlivých scénářů:
- [x] 1. SSH => EXEC => EXEC
- [x] 2. EXEC => EXEC
- [ ] 3. SSH => EXEC => PBS
- [ ] 4. SSH => PBS => SSH => PBS
- [x] 5. SSH => EXEC => SSH => EXEC
- [x] 6. EXEC => SSH => EXEC
- [ ] 7. EXEC  => SSH => PBS

**Comment by johnymachine** [comment]
1. SSH => EXEC => EXEC

Je nějaký důvod proč by opětovné spuštění mělo trvat déle?

Při druhém spuštění to dlouho stojí zde: (podle logu 10 min oproti 1:30 na poprvé)

**DELEGATOR:***
[delegator.txt](https://github.com/GeoMop/GeoMop/files/38839/delegator.txt)
2015-11-19 11:43:21,303 DEBUG Message is resent
2015-11-19 11:43:21,303 DEBUG json:{}
2015-11-19 11:43:21,304 DEBUG Answer to resent message is receive (type:action_in_process, action{})
2015-11-19 11:43:21,304 DEBUG json:{}
2015-11-19 11:43:21,305 DEBUG Answer is sent (type:action_in_process, action{})
2015-11-19 11:43:23,408 DEBUG Input message is receive (type:installation, action{})

**MJ_SERVICE:**
[mj_service.txt](https://github.com/GeoMop/GeoMop/files/38838/mj_service.txt)
2015-11-19 11:39:25,549 DEBUG Input message is receive (type:installation, action{})
2015-11-19 11:39:25,549 DEBUG Installation in process signal was sent
2015-11-19 11:39:25,549 DEBUG json:{}
2015-11-19 11:39:25,549 DEBUG Answer is sent (type:action_in_process, action{})

**Comment by richtertul** [comment]
Je potřeba Instalaci udělat tak, aby se při opakovaném spuštění neprováděla znova. Podívám se na to přes týden, zatím to na remotu vždy po sobě smaž. Dále je nutné vždy zkontrolovat, aby na remote nezůstali viset processy. Příkazy:
ps -u pavel.richter
qstat pro pbs

**Comment by johnymachine** [comment]
Procesy jsem zkontroloval a případně zabil.

V budoucnu na to bude sloužit restore_connection že?
(Asi by bylo, ověřit jestli je opravdu nainstalovano)

Jinak po skončení jobu to uzavírám a obvykle se všechno ukončí a procesy jsou ukončeny.

**Comment by richtertul** [comment]
Restore connection by měla již fungovat a měla by to umět vrátit v případě přerušení spojení. Pokud jde o instalaci, asi tam udělám nějaké souborové zámky, už to mám rozmyšlené.

**Comment by johnymachine** [comment]
8. EXEC => EXEC
Vypadá to, že tam nemáš ošetření pro lokální běh. ExecOutputComm nemá connected.
Tohle se děje v té aktuální verzi ode mne.

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dev/Repos/GeoMop/src/JobsScheduler/communication/jobs_communicator.py", line 172, in _run_action
    action(self.next_communicator,self.mj_name, id)
  File "/home/dev/Repos/GeoMop/src/JobsScheduler/communication/exec_output_comm.py", line 49, in exec_
    process = subprocess.Popen(self.installation.get_args(python_file, mj_name, mj_id),
  File "/home/dev/Repos/GeoMop/src/JobsScheduler/communication/installation.py", line 216, in get_args
    dest_path = self.copy_path + '/' + __ins_files__[name]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'



Traceback (most recent call last):
  File "/home/dev/Repos/GeoMop/src/JobsScheduler/mj_service.py", line 95, in <module>
    comunicator.run()
  File "/home/dev/Repos/GeoMop/src/JobsScheduler/communication/communicator.py", line 427, in run
    self.idle_func()
  File "/home/dev/Repos/GeoMop/src/JobsScheduler/communication/jobs_communicator.py", line 135, in job_idle_func
    if not self.job_outputs[id].connected and self.job_outputs[id].initialized:
AttributeError: 'ExecOutputComm' object has no attribute 'connected'

**Comment by richtertul** [comment]
Ano do větve kam si se dostal toho není ošetřeno docela dost. (pracuji na tom). Otázka je jak si se tam dostal, když jsi zkoušel exec-exec, protože to bylo dělaný pro pbs (s kterým si měl počkat). Deset minut po tom co jsi to poslal jsem se šel na to podívat a už si byl asi na cestě domů. Minimálně pokud dáš Exec-Exec by se ti neměl otevřít delegator, který ale máš jako next_communicator v configu. Bylo by potřeba, aby jsi v případě chyby zkontroloval alespon svojí stranu, před tím než okopíruješ a pošleš log.

**Comment by johnymachine** [comment]
Myslím si, že jsem to udělal správně, jelo to na následujícím teď jsem to ověřoval.

[app.txt](https://github.com/GeoMop/GeoMop/files/44765/app.txt)
[job.txt](https://github.com/GeoMop/GeoMop/files/44767/job.txt)
[mj_service.txt](https://github.com/GeoMop/GeoMop/files/44766/mj_service.txt)

**Comment by johnymachine** [comment]
SSH => EXEC => SSH => EXEC

Zdá se bez problému.

**Comment by johnymachine** [comment]
EXEC => SSH => EXEC

Nekorektně se obnovuje spojení nevyskočí, žádná chyba. V logu jsem našel tento problém:

2015-11-26 13:11:34,829 INFO Application app is interupted
2015-11-26 13:11:34,829 INFO Application app is interupted
2015-11-26 13:11:37,950 DEBUG Status loaded from /home/dev/Repos/GeoMop/src/JobsScheduler/jobs/EXEC_SSH_EXEC/status/app.json
2015-11-26 13:11:37,950 DEBUG Status loaded from /home/dev/Repos/GeoMop/src/JobsScheduler/jobs/EXEC_SSH_EXEC/status/app.json
2015-11-26 13:11:37,952 DEBUG Status saved to  /home/dev/Repos/GeoMop/src/JobsScheduler/jobs/EXEC_SSH_EXEC/status/app.json
2015-11-26 13:11:37,952 DEBUG Status saved to  /home/dev/Repos/GeoMop/src/JobsScheduler/jobs/EXEC_SSH_EXEC/status/app.json
2015-11-26 13:11:37,952 INFO Application app is restored
2015-11-26 13:11:37,952 INFO Application app is restored
2015-11-26 13:11:37,953 DEBUG json:{}
2015-11-26 13:11:37,953 DEBUG json:{}
2015-11-26 13:11:37,954 DEBUG Message is send (type:restore_connection, action{})
2015-11-26 13:11:37,954 DEBUG Message is send (type:restore_connection, action{})
2015-11-26 13:11:37,954 WARNING Error(Invalid message length) during parsing output answer: 
2015-11-26 13:11:37,954 WARNING Error(Invalid message length) during parsing output answer: 
2015-11-26 13:11:37,955 DEBUG Answer to message is receive (None)
2015-11-26 13:11:37,955 DEBUG Answer to message is receive (None)

**Comment by richtertul** [comment]
EXEC-EXEC - opraven, prosím otestovat
Jobs state - zobrazuje reálný stav dvou jobů, které běží 3 minuty. Při testování nutno testovat že probíhají v pořádku.

**Comment by johnymachine** [comment]
EXEC-EXEC
Komunikace fungovala správně. (Spustit / Pozastavit / Obnovit / Ukončit)

Joby podle MPI logu také proběhly, ale i po skončení to stále hlásí do aplikace running. Navíc to vypadá, že se neukončí korektně, zbyly mi tam na pozadí 3 procesy:

job.py EXEC_EXEC test1 & disown
job.py EXEC_EXEC test2 & disown
mj_service.py EXEC_EXEC & disown

**Comment by johnymachine** [comment]
HYDRA_EXEC
jobs_communicator:183 asi kolize jmen a importu

  File "/home/dev/Repos/GeoMop/src/JobsScheduler/communication/jobs_communicator.py", line 183, in job_idle_func
    if self.conf.output_type != self.conf.OutputCommType.ssh or \
AttributeError: 'CommunicatorConfig' object has no attribute 'OutputCommType'

**Comment by johnymachine** [comment]
HYDRA_EXEC
mi nevrací joby a v logu je jen toto

2015-12-11 14:04:51,392 INFO Application stop for uncatch error:[Errno 32] Broken pipe

mpicc nastaveno na: /opt/mpich2/gnu/bin/mpicc
